# Generated by Django 4.0.7 on 2024-09-28 14:15

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_subscribe_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='id',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5e60517a-cf8d-4ebc-ab34-b85a0a69d627'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('subscriber', 'target')},
        ),
    ]
